import { useEffect, useState, type FormEvent } from "react";
import { Archive, KeyRound, Pencil, Plus, RefreshCw, Save, Send, ShieldCheck, Trash2 } from "lucide-react";
import type { CredentialLeakPageResult, CredentialLeakRecord, CredentialSubscription, PublicationModule, TenantPublicationPolicy } from "@sentinel/shared";
import { Button, IconButton, Modal, Panel, Tag } from "@/components/common";
import { DeleteConfirmation, PageHeader, Toast, type ToastState } from "@/components/business/AdminPrimitives";
import { adminApiFetch as apiFetch } from "@/api/admin";

const moduleMeta: Record<PublicationModule, { label: string; description: string }> = {
  sensitive: { label: "敏感信息", description: "账号口令、源码、文档与仿冒网站" },
  asset: { label: "资产信息", description: "资产基线及后续状态差异" },
  "dark-web": { label: "暗网情报", description: "暗网文章与证据附件" },
  credentials: { label: "账号凭据", description: "凭据订阅接口采集结果" },
  vulnerabilities: { label: "漏洞情报", description: "漏洞 Feed 与手工维护数据" }
};

export function PublicationPoliciesPage({ tenantId }: { tenantId: string }) {
  const [policies, setPolicies] = useState<TenantPublicationPolicy[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [toast, setToast] = useState<ToastState>(null);
  const load = () => apiFetch<TenantPublicationPolicy[]>(`/api/tenant-publication-policies?tenant_id=${encodeURIComponent(tenantId)}`).then(setPolicies);
  useEffect(() => { setLoading(true); load().catch((error) => setToast({ tone: "warning", text: error.message })).finally(() => setLoading(false)); }, [tenantId]);
  const save = async () => { setSaving(true); try { setPolicies(await apiFetch<TenantPublicationPolicy[]>(`/api/tenant-publication-policies?tenant_id=${encodeURIComponent(tenantId)}`, { method: "PUT", body: JSON.stringify({ policies }) })); setToast({ tone: "success", text: "当前客户的发布策略已保存" }); } catch (error) { setToast({ tone: "warning", text: error instanceof Error ? error.message : "发布策略保存失败" }); } finally { setSaving(false); } };
  return <><PageHeader eyebrow="TENANT DELIVERY POLICY" title="发布策略" description="分别控制当前客户各业务板块是采集后自动发送，还是审核通过后再发送到地端。" actions={<Button onClick={() => void save()} disabled={loading || saving}><Save size={16} />{saving ? "保存中..." : "保存策略"}</Button>} />
    <Panel><div className="policy-table"><div className="policy-table-head"><span>业务板块</span><span>数据范围</span><span>发送方式</span></div>{policies.map((policy) => <div className="policy-table-row" key={policy.module}><div><strong>{moduleMeta[policy.module].label}</strong><small>{policy.module}</small></div><span>{moduleMeta[policy.module].description}</span><div className="policy-segment" role="group" aria-label={`${moduleMeta[policy.module].label}发送方式`}><button className={policy.mode === "auto" ? "active" : ""} onClick={() => setPolicies((items) => items.map((item) => item.module === policy.module ? { ...item, mode: "auto" } : item))}>自动发送</button><button className={policy.mode === "approval" ? "active" : ""} onClick={() => setPolicies((items) => items.map((item) => item.module === policy.module ? { ...item, mode: "approval" } : item))}>审批后发送</button></div></div>)}</div>{loading && <div className="inline-empty"><RefreshCw className="is-spinning" size={22} /><strong>正在加载发布策略</strong></div>}</Panel>
    <div className="policy-default-note"><ShieldCheck size={17} /><span>默认策略：漏洞情报、账号凭据自动发送；敏感信息、资产信息、暗网情报审批后发送。</span></div><Toast value={toast} onClose={() => setToast(null)} /></>;
}

export function CredentialOperationsPage({ tenantId }: { tenantId: string }) {
  const [subscriptions, setSubscriptions] = useState<CredentialSubscription[]>([]); const [selectedId, setSelectedId] = useState<number | null>(null);
  const [records, setRecords] = useState<CredentialLeakPageResult | null>(null); const [loading, setLoading] = useState(true); const [toast, setToast] = useState<ToastState>(null);
  const [publishingId, setPublishingId] = useState(""); const [editing, setEditing] = useState<CredentialLeakRecord | null | undefined>(undefined); const [deleting, setDeleting] = useState<CredentialLeakRecord | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { setLoading(true); apiFetch<CredentialSubscription[]>(`/api/credentials/subscriptions?tenant_id=${encodeURIComponent(tenantId)}`).then((items) => { setSubscriptions(items); setSelectedId(items[0]?.id ?? null); if (!items.length) setRecords(null); }).catch((error) => setToast({ tone: "warning", text: error.message })).finally(() => setLoading(false)); }, [tenantId]);
  const loadRecords = () => selectedId ? apiFetch<CredentialLeakPageResult>(`/api/credentials/results?tenant_id=${encodeURIComponent(tenantId)}&sub_id=${selectedId}&page_size=100`).then(setRecords) : Promise.resolve();
  useEffect(() => { if (!selectedId) return; setLoading(true); loadRecords().catch((error) => setToast({ tone: "warning", text: error.message })).finally(() => setLoading(false)); }, [tenantId, selectedId]);
  const selected = subscriptions.find((item) => item.id === selectedId);
  const publish = async (id: string) => { setPublishingId(id); try { await apiFetch(`/api/credentials/records/${encodeURIComponent(id)}/publish`, { method: "POST", body: JSON.stringify({ tenantId }) }); setRecords((current) => current ? { ...current, data: current.data.map((item) => item.id === id ? { ...item, isPublished: true, reviewedAt: new Date().toISOString() } : item) } : current); setToast({ tone: "success", text: "账号凭据已确认发送" }); } catch (error) { setToast({ tone: "warning", text: error instanceof Error ? error.message : "账号凭据发送失败" }); } finally { setPublishingId(""); } };
  const saveRecord = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const body = { tenantId, subId: Number(form.get("subId")), systemName: form.get("systemName"), url: form.get("url"), account: form.get("account"), password: form.get("password"), leakedAt: form.get("leakedAt"), source: form.get("source") }; try { await apiFetch(editing ? `/api/credentials/records/${encodeURIComponent(editing.id)}` : "/api/credentials/records", { method: editing ? "PUT" : "POST", body: JSON.stringify(body) }); setEditing(undefined); await loadRecords(); setToast({ tone: "success", text: editing ? "账号凭据已更新" : "账号凭据已新增" }); } catch (error) { setToast({ tone: "warning", text: error instanceof Error ? error.message : "账号凭据保存失败" }); } finally { setSaving(false); } };
  const removeRecord = async () => { if (!deleting) return; setSaving(true); try { await apiFetch(`/api/credentials/records/${encodeURIComponent(deleting.id)}`, { method: "DELETE", body: JSON.stringify({ tenantId }) }); setRecords((current) => current ? { ...current, total: Math.max(0, current.total - 1), allTotal: Math.max(0, (current.allTotal || current.total) - 1), data: current.data.filter((item) => item.id !== deleting.id) } : current); setDeleting(null); setToast({ tone: "success", text: "账号凭据已删除" }); } catch (error) { setToast({ tone: "warning", text: error instanceof Error ? error.message : "账号凭据删除失败" }); } finally { setSaving(false); } };
  return <><PageHeader eyebrow="CREDENTIAL INTELLIGENCE" title="账号凭据" description="维护当前客户的凭据泄露数据，并按发布策略发送到地端。" actions={<Button onClick={() => setEditing(null)} disabled={!subscriptions.length}><Plus size={16} />新增凭据</Button>} />
    <div className="credential-ops-layout"><Panel title="订阅范围"><div className="credential-subscriptions">{subscriptions.map((item) => <button key={item.id} className={item.id === selectedId ? "active" : ""} onClick={() => setSelectedId(item.id)}><span><KeyRound size={15} /><strong>{item.value}</strong></span><small>{item.targetName || item.targetId} · 已存 {item.storedCount ?? item.count} 条</small></button>)}{!subscriptions.length && !loading && <div className="inline-empty"><KeyRound size={24} /><strong>当前客户暂无凭据订阅</strong></div>}</div></Panel>
      <Panel title={selected ? `泄露明细 · ${selected.value}` : "泄露明细"}><div className="credential-record-table"><div className="credential-record-head"><span>系统 / 地址</span><span>账号</span><span>口令</span><span>来源</span><span>发现时间</span><span>发送状态</span><span>操作</span></div>{records?.data.map((record) => <div className="credential-record-row" key={record.id}><div><strong>{record.systemName}</strong><small>{record.url}</small></div><code>{record.account || "--"}</code><code>{record.password || "--"}</code><span>{record.source}</span><time>{record.firstSeenAt?.replace("T", " ").slice(0, 19) || record.leakedAt}</time><Tag tone={record.isPublished === false ? "orange" : "green"}>{record.isPublished === false ? "待发送" : "已发送"}</Tag><div className="credential-row-actions"><IconButton label="编辑凭据" onClick={() => setEditing(record)}><Pencil size={14} /></IconButton><IconButton label="删除凭据" className="danger-icon-button" onClick={() => setDeleting(record)}><Trash2 size={14} /></IconButton>{record.isPublished === false && <IconButton label="审核并发送" disabled={publishingId === record.id} onClick={() => void publish(record.id)}><Send size={14} /></IconButton>}</div></div>)}{!records?.data.length && !loading && <div className="inline-empty"><Archive size={24} /><strong>该订阅暂无泄露明细</strong></div>}</div></Panel></div>
    <Modal open={editing !== undefined} title={editing ? "编辑账号凭据" : "新增账号凭据"} onClose={() => !saving && setEditing(undefined)} footer={<><Button variant="ghost" onClick={() => setEditing(undefined)} disabled={saving}>取消</Button><Button type="submit" form="credential-record-form" disabled={saving}>{saving ? "保存中..." : "保存凭据"}</Button></>}><form id="credential-record-form" className="admin-form" onSubmit={saveRecord}><label>凭据订阅<select name="subId" required defaultValue={editing?.subId || selectedId || ""}>{subscriptions.map((item) => <option key={item.id} value={item.id}>{item.value} · {item.subCategory}</option>)}</select></label><div className="form-grid"><label>系统名称<input name="systemName" required defaultValue={editing?.systemName || ""} /></label><label>系统地址<input name="url" required defaultValue={editing?.url || ""} placeholder="https://example.com" /></label><label>泄露账号<input name="account" required defaultValue={editing?.account || ""} /></label><label>泄露口令<input name="password" required defaultValue={editing?.password || ""} /></label><label>情报来源<input name="source" required defaultValue={editing?.source || "手工录入"} /></label><label>泄露时间<input name="leakedAt" required defaultValue={editing?.leakedAt || new Date().toISOString().slice(0, 16)} /></label></div></form></Modal>
    <DeleteConfirmation open={Boolean(deleting)} title="删除账号凭据" subject={deleting ? `${deleting.systemName} · ${deleting.account}` : ""} warning="删除后该条凭据将不再进入后续地端快照。" confirming={saving} onClose={() => setDeleting(null)} onConfirm={() => void removeRecord()} />
    {loading && <div className="tenant-page-loading"><RefreshCw className="is-spinning" size={18} />正在刷新当前客户数据</div>}<Toast value={toast} onClose={() => setToast(null)} /></>;
}
