#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_LABEL="运营平台"
DEPLOY_COMPOSE_FILE="docker-compose.cloud.production.yml"
DEPLOY_ENV_POINTER="SENTINEL_CLOUD_ENV_FILE"
DEPLOY_ENV_DEFAULT=".env.production"
DEPLOY_ENV_EXAMPLE=".env.production.example"
DEPLOY_ENTRY_NAME="cloud-docker.sh"
DEPLOY_REQUIRED_KEYS="POSTGRES_PASSWORD DATABASE_URL REDIS_URL SENTINEL_SECRET SENTINEL_ADMIN_PASSWORD SENTINEL_PORTAL_PASSWORD SENTINEL_PUBLIC_BASE_URL SENTINEL_TLS_CERT_HOST_PATH SENTINEL_TLS_KEY_HOST_PATH"
DEPLOY_FILE_KEYS="SENTINEL_TLS_CERT_HOST_PATH SENTINEL_TLS_KEY_HOST_PATH"
DEPLOY_HTTPS_URL_KEY="SENTINEL_PUBLIC_BASE_URL"
DEPLOY_PUBLIC_URL_KEY="SENTINEL_PUBLIC_BASE_URL"
DEPLOY_URL_PATH="/admin"

source "$SCRIPT_DIR/_docker-deploy.sh"
docker_deploy "${1:-start}"
